site_url = "https://canada.constructconnect.com/dcn/certificates-and-notices"
company_name = "Pioneer Construction Inc."
# company_name = "Lafarge"
# location = "Fort Francis"
# location = "Kenora"
# location = "Red Lake"